### ISSUE TITLE
Could you please add a MIT license?

### ISSUE THREAD

**Issue by VigneshVSV** [datenwolf/PyPhytron#1]
Your project needs to be copied for internal use, I dont wish to run to license issues when re-publishing. 

Another license like BSD is also alright!

**Comment by datenwolf** [comment]
Hi VingeshVSV, it's nice to know that my code from my time working at the Garching accelerator lab seems to be still in use there. Since I originally wrote the code under contract with the LMU, I think you or I will to actually have to ask LMU legal, if they're okay with going with an MIT license (it's actually "their" code, after all, legally speaking).

**Comment by VigneshVSV** [comment]
Thanks a lot for this clarification! 

I didnt know you worked here :P 

Yes, we would like to release in LMU's MIT license, I was not sure how it ended up here so I was asking to add the license. We did make significant changes/improvements though. Only the structure and core ideas based on this code is visible in our package. 

In short, LMU already gave its permission.

**Comment by datenwolf** [comment]
I think the original reason for the code ending up here was, that we didn't have an internal Git repository back then. We (Klaus Steinberger, Susanna Maurer) were discussing it, but I left LMU before there was a centralized repo store. So I put the sources on GitHub to keep them around somewhere "safe".

I created PyPhytron for the rework of the ERDA-Step system (see my diploma thesis https://dl.datenwolf.net/diplomarbeit.pdf  page 54ff).

**Comment by VigneshVSV** [comment]
Thanks a lot, I will keep this issue open until the repository is made public (should be made in < 2 weeks). 

If you are interested, you can add any links and license info from there (I will share the public link soon enough).

**Comment by datenwolf** [comment]
MIT license added

Please pass on my regards to Jörg Schreiber

**Comment by VigneshVSV** [comment]
Great! I just checked it. 

I will close the issue then.

**Comment by VigneshVSV** [comment]
https://gitlab.lrz.de/cala-public/packages/pyphymotion
